=

diff --git a/.github/workflows/ccid.yml b/.github/workflows/ccid.yml
--- a/.github/workflows/ccid.yml
+++ b/.github/workflows/ccid.yml
@@ -22,7 +22,7 @@ jobs:
 
       - name: Copying the files to ngx folder
         run: |
-          sudo mv dist/* /var/www/portfolio/ && echo "Files moved successfully." || echo "Failed to move files."
+          sudo mv dist/* /var/www/portfolio && echo "Files moved successfully." || echo "Failed to move files."
 
       - name: Reload Nginx
         run: |
